sudo: required
services:
    - docker
script:
    - docker build -t jostino/node .
    - docker images jostino/node

before_deploy:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
deploy:
    provider: script
    script: docker push jostino/node
    on:
        branch: master